### ISSUE TITLE
How to exec command in the pod/container?

### ISSUE THREAD

**Issue by nettyxiong** [kubernetes-client/python#1058]
```python
    def execCmdInPod(self, pod_name, cmd, timeout):
        name = pod_name
        namespace = 'default'
        try:
            resp = stream(self.m_api_instance.connect_get_namespaced_pod_exec, name, namespace, command=cmd,
                          stderr=True, stdin=False,
                          stdout=True, tty=False,
                          _preload_content=True,
                          _request_timeout=timeout)
        except Exception, e:
            if self.__validLogger():
                self.m_logger.error('Exec cmd "%s" in pod "%s" failed, the detail error msg is:"%s"', cmd,
                                    traceback.format_exc())
            return False
        return True  # execCmdInPod()

cmd = ["bash", "-c", "python start.py > start.log"]
execCmdInPod("test",  cmd, timeout=180)
```
I use below code to exec a script in the pod/container(only one container in the pod), but I use the _request_timeout=180 to wait the scipt exec finished.
The problem :
 If I use no timeout setting, then the script would not be executed in the pod/container.
I just wan't to know how to exec a script from the container in sync mode.

**Comment by nettyxiong** [comment]
And How can I get the result which stands for the script excuting result?

**Comment by nettyxiong** [comment]
@roycaihw Could you help me?

**Comment by roycaihw** [comment]
@nettyxiong Have you checked [this example](https://github.com/kubernetes-client/python/blob/master/examples/pod_exec.py)?

**Comment by nettyxiong** [comment]
@roycaihw
Yes, I just copy code snippet from the `pod_exec` example.
I just add the timeout param.

> The problem :
> If I use no timeout setting, then the script would not be executed in the pod/container.
> I just wan't to know how to exec a script from the container in sync mode.

And now I try to give up this python client instead of using kubectl binary tool with subprocess.

**Comment by roycaihw** [comment]
> If I use no timeout setting, then the script would not be executed in the pod/container.

Which version of this client are you using? I couldn't reproduce this locally. Could you elaborate more on what you mean by "sync mode"? 

My suspicion is that your script takes a long time to finish. And I found a bug in our code where the timeout didn't get defaulted https://github.com/kubernetes-client/python/issues/1085. As a result the client hung waiting for the script to finish / server-side timeout to be reached. 

On the other side, currently the client doesn't throw an error when the timeout is reached, so you won't be able to detect it. I filed https://github.com/kubernetes-client/python/issues/1086 to collect more feedback

> And How can I get the result which stands for the script excuting result?

When you run `python start.py > start.log`, the result gets piped to the container's file system tree. You need to use stdout or stderr instead so that the client can get the result back.

**Comment by nettyxiong** [comment]
1. The client version is : 11.0.0-snapshot
2. If I set no timeout param, the exec would be hung for a long time, so I set timeout=180. 
But I found that the `start.py` script finished  in 120s and just would be hung until timeout trigger, even the script has run completely.
3. The `sync mode`  which means that exec a cmd until the cmd run completely or timeout trigger(not just based on the timeout trigger), and can get it's result feedback easily

**Comment by roycaihw** [comment]
> But I found that the start.py script finished in 120s and just would be hung until timeout trigger, even the script has run completely

I think we need a way to reproduce this (either via an e2e test or with some pod spec and command). I couldn't reproduce this issue locally by adding a `sleep 120` to [this example](https://github.com/kubernetes-client/python/blob/f493272827ed31575b87a522a4206f446a1e12f6/examples/pod_exec.py#L73) before the message printing
