### ISSUE TITLE
ProxyError('Cannot connect to proxy.', error('Tunnel connection failed: 407 authentication required',))

### ISSUE THREAD

**Issue by erlisb** [kubernetes-client/python#1063]
**What happened (please include outputs or screenshots)**:
I am trying to use proxy in the kubernetes framework but I get the following error : 
```
 urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='lcageanaksd-1dffcee1.hcp.westeurope.azmk8s.io', port=443): Max retries exceeded with url: /api/v1/nodes (Caused by ProxyError('Cannot connect to proxy.', error('Tunnel connection failed: 407 authentication
required',)))
```
**What you expected to happen**:
Here I suppose I would get the list of nodes.

**How to reproduce it (as minimally and precisely as possible)**:

        self.client_config = Configuration()
        self.client_config.debug = False
        self.client_config.verify_ssl = ssl
        self.client_config.assert_hostname = False
        self.client_config.host = url
        self.client_config.proxy = proxy_url
        self.client_config.debug = True
        self.client_config.api_key.update({'Authorization': 'Bearer {}'.format(TOKEN)})
        ApiClient = client.ApiClient(self.client_config)
        v1 = client.CoreV1Api(ApiClient)
       v1.list_node()
**Anything else we need to know?**:

**Environment**:
Kubernetes Client Version: v1.11.0+d4cacc0
AKS Kubernetes Server Version: v1.12.7
Python 2.7.15rc1

**Comment by roycaihw** [comment]
You need to pass in proxy headers to properly use the proxy manager. Ref https://github.com/kubernetes-client/python/pull/779, https://github.com/OpenAPITools/openapi-generator/pull/2467

This should be fixed in the upcoming [12.0.0a1](https://github.com/kubernetes-client/python/pull/1088) release where we upgrade to a newer version of openapi-generator. You can apply the fix locally as a workaround
