### ISSUE TITLE
Websocket call should throw an error when client-side timeout is reached

### ISSUE THREAD

**Issue by roycaihw** [kubernetes-client/python#1086]
**What is the feature and why do you need it**:
Currently when you run websocket call with a timeout, e.g. 
```
    resp = stream(api_instance.connect_get_namespaced_pod_exec,
                  name,
                  'default',
                  command=exec_command,
                  stderr=True, stdin=False,
                  stdout=True, tty=False,
                  timeout=60)
```
the client doesn't raise any error when the [timeout is reached](https://github.com/kubernetes-client/python-base/blob/a25f49eb41a28b5ffafb309f26e182b80ec747de/stream/ws_client.py#L224-L233). It only keeps whatever data that has been sent back through the channels. 

**Describe the solution you'd like to see**:
Potentially we can throw an error so that user application can get notified and handle it (e.g. the case in https://github.com/kubernetes-client/python/issues/1058#issue-550582050). 

I'm not sure if this will be an improvement to the usability of this client, or if people are satisfied with the current behavior. I'm opening this issue to collect more feedback.

**Comment by eguiller-pr** [comment]
/reopen
Hi @roycaihw,
Which is at the moment the way to figure out that the web socket connection has ended with timeout?
I am trying to use the run_forever method and afterward check if the connection is still open.

**Comment by MrEcco** [comment]
This issue is still relevant. Let me give you more details.

If your Kubernetes cluster is partially broken (e.g. single-node failure), and you try to execute a command in the pod on the unreachable node, then the websocket connection attempt is too long and completely ignores the explicitly defined timeout. It's always 30 seconds.

* Yes, it's usually in case of issues with cluster. I haven't managed to reproduce it on a healthy cluster.
* However, I'm trying to apply some python automation for collecting the issues of the broken cluster. That's the reason why I need it even on the broken cluster.
* Tried providing `timeout` and `_request_timeout`, in both formats `5` and `(1,4)`, nothing helps
