### ISSUE TITLE
Add example about using server-side apply with this client

### ISSUE THREAD

**Issue by tdmalone** [kubernetes-client/python#1093]
**What is the feature and why do you need it**:

I would like to have an 'apply' (patch) mode for the helpful [`create_from_yaml`/`create_from_dict`](https://github.com/kubernetes-client/python/blob/master/kubernetes/utils/create_from_yaml.py) utility methods.

I currently use this to automate deployment of our application, however from time-to-time something goes wrong in the deployment and we need to deploy it again. At the moment we can't re-run the automation, because parts of it fail due to some objects having already been created.

I'm looking at catching the `FailToCreateError` and checking for `reason: "AlreadyExists"`, but at this point it would be wonderful to be able to run `create_from_yaml` in an 'apply'/patch mode, rather than have to build out the full request myself.

**Describe the solution you'd like to see**:

Probably something as simple as an `apply=True` or `patch=True` argument on these methods could do the job?

**Comment by roycaihw** [comment]
[Server-side apply](https://github.com/kubernetes/enhancements/issues/555) has been beta since 1.15, we should add example/utility about how to use it with the 11.0 client.

**Comment by MoShitrit** [comment]
Hey @tdmalone & @roycaihw!
I'm willing to start contributing to this project, and this issue seems like it might be a great first one to begin with!
So I just wanted to make sure I have the right idea in mind- is the goal here to add an additional `apply/patch` logic to https://github.com/kubernetes-client/python/blob/master/kubernetes/utils/create_from_yaml.py? I didn't dive in too deep yet, but from a quick glimpse, it seems like adding a method `apply_from_yaml_single_item` and calling it when `apply=True` was passed could do it.
Alternatively, we can probably separate that entirely by creating a whole new module for `apply_from_yaml.py`, but I assume there will be a good bit of repetition if we take that route.
Either way, I'd love to take a stab at this! Please let me know how we can kick off a quick discussion around it.
Thanks much, and I'm looking forward to start working on that!

**Comment by roycaihw** [comment]
@MoShitrit Welcome and thanks for looking into this issue! 

Yes I think the goal is to add an apply mode to the utility methods, either adding an `apply=True` option or automatically retrying when an `AlreadyExists` error is returned. To achieve that I think we should use the new server-side apply feature (implementing a client-side apply like `kubectl apply` from scratch will be expensive and doesn't make much sense when we have server-side apply almost ready).

To begin with, I think we can first add an example about how to use this API in the python client. According to the [doc](https://kubernetes.io/docs/reference/using-api/api-concepts/#server-side-apply), a client requests a server-side apply by sending an API request to any PATCH endpoint with content type `application/apply-patch+yaml` and a partially specified object in the body. 

Did a little research and I think there are currently two blockers for using this API in the python client: 
1. although server-side apply targeted to be beta in 1.15, it seems that it actually went beta in 1.16 (as the [doc](https://kubernetes.io/docs/reference/using-api/api-concepts/#server-side-apply) shows). For this client, we do code-generation based on the upstream openapi spec. The problem is that the [1.15 openapi spec](https://github.com/kubernetes/kubernetes/blob/release-1.15/api/openapi-spec/swagger.json) didn't specify `application/apply-patch+yaml` as acceptable content type. And [1.16 openapi spec](https://github.com/kubernetes/kubernetes/blob/release-1.16/api/openapi-spec/swagger.json) specified that. As a result, the generated client will only have `application/apply-patch+yaml` concept starting 1.16 (12.0.0a1+)
2. there is a known issue about choosing content-type for PATCH methods. See https://github.com/kubernetes-client/python/pull/959

**Comment by kwiesmueller** [comment]
Hey there,
we are currently investigating options for adding apply to client-go. If you need help with adding it to the python client, feel free to get in touch on Slack https://kubernetes.slack.com/archives/C0123CNN8F3
I'm adding our label to put this on our list as well.
/wg api-expression

**Comment by themrmax** [comment]
@MoShitrit how did you go with this? i would very much like this feature

**Comment by MoShitrit** [comment]
> @MoShitrit how did you go with this? i would very much like this feature

Hey @themrmax 
I haven't really looked at it since. Might be a good time to re-evaluate, given that it's been about a year and we passed a few versions and iterations already.
If anyone's willing to take a stab at it- please feel free. Otherwise I'll try myself whenever I can put some time aside to do so.
Thanks!

/reopen

**Comment by Jc2k** [comment]
I believe this PR from 2019 would enable the use of server side apply? https://github.com/kubernetes-client/python/pull/959. It enables you to set the content type, and AIUI that means you can do `content_type=application/apply-patch+yaml` when calling any patch API and enjoy SSA.

**Comment by madkinsz** [comment]
It'd be great to know if this feature was available without subclassing the client. Are there any existing examples of using server-side apply from the Python client?

**Comment by Jc2k** [comment]
I am still adding a subclass to every project, unfortunately.

**Comment by portswigger-tim** [comment]
Anyone who lands here... there's an example within the tests: https://github.com/kubernetes-client/python/blob/56eea103a761c2310af76c63d4ed9cdd7171aeed/kubernetes/base/dynamic/test_client.py#L512-L532

**Comment by jbnjohnathan** [comment]
2 years since Server-Side apply was introduced in Kubernetes 1.22. Would be great to get to use it fully in this kubernetes python client soon.
