### ISSUE TITLE
how to replace deployment force?  this method can't do force replace(replace_namespaced_deployment),when i use kubectl replcae --force it can force replace

### ISSUE THREAD

**Issue by jtl0813** [kubernetes-client/python#1147]
**Link to the issue (please include a link to the specific documentation or example)**:

**Description of the issue (please include outputs or screenshots if possible)**:

**Comment by MoShitrit** [comment]
Hey @jtl0813 
Actually, when you run your `kubectl replace --force` command, it performs two actions under the hood- it deletes and then applies the deployment yaml from the provided file. You can also see that from the output of the command, there are two consecutive lines saying 
```
deployment "foo" deleted
deployment "foo" created/applied
```
So in order to replicate that behavior in python client, I would say your best shot is to split your action in two calls - `delete_namespaced_deployment` and then `create_namespaced_deployment`. That's only relevant for cases in which you need the `--force` option. Otherwise, calling `replace_namespaced_deployment` should suffice.
You can also see in k8s api reference doc, that `force` option doesn't really exist for calls to `replace` - https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.17/#replace-deployment-v1-apps.

Hope it helps!!

**Comment by jtl0813** [comment]
thanks fou your help,I was try to use your method  (delate and create) to  manage deployment,I hava no yaml files, The app is managed by helm ,the create_namespaced_deployment method need the yaml file ,if use read_namespaced_deployment methos to get deployment object and use it to replace yaml ,  create_namespaced_deployment   returns  follows notice    
{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"resourceVersion should not be set on objects to be created","code":500}.

**Comment by MoShitrit** [comment]
Hey @jtl0813!
Unfortunately, not having the resource file would complicate things a bit for you.
For the moment, as long as you use k8s version older than 1.18 - you can provide a parameter to `read_namespaced_deployment()` of `export=True`, which is the equivalent of `--export` on `kubectl`. However, this feature is deprecated and is going away with the release of k8s 1.18 (see https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.14.md#deprecations and https://github.com/kubernetes/kubernetes/pull/73787 for additional context).
The `export` option will strip out fields such as `resourceVersion` which shouldn't be specified on a manifest that you try to apply/create, but rather it's auto-generated by the api on the time of creation.
Once `export` has been removed in version 1.18, your only other option would be to manually remove all the fields that aren't relevant, such as `resourceVersion`, `namespace` (if moving to a different namespace) and so on.
At the moment- it doesn't look like there's any plan to add an alternative server-side option for `export` and it'll be down to specific users to implement their own specific methods in handling this scenario.

**Comment by jtl0813** [comment]
got it,thank you!

**Comment by roycaihw** [comment]
/close

Thanks @MoShitrit for answering the issue!
