### ISSUE TITLE
en...

### ISSUE THREAD

**Issue by biwenKey** [kubernetes-client/python#1207]
**Link to the issue (please include a link to the specific documentation or example)**:

**Description of the issue (please include outputs or screenshots if possible)**:
![image](https://user-images.githubusercontent.com/27846351/88049413-afe0f300-cb87-11ea-9b87-f3c9ddb292ac.png)

**Comment by roycaihw** [comment]
The core v1 API group is huge for legacy reason. The doc is generated from the upstream openapi spec by the openapi-generator. I think the issue applies to all the generated clients (e.g. [the java client](https://github.com/kubernetes-client/java/blob/master/kubernetes/docs/CoreV1Api.md)) as well. You could download the raw file and view it with a different render that supports larger files than Github

**Comment by aalexanderr** [comment]
Until the issue is fixed, this might help some people. Written for complete newbies so no one should have problems with it (if you use *nix)

Required tools:
1. Bash
1. [Pandoc](https://pandoc.org/installing.html) for rendering markdown files to html.
1. A template for pandoc, the default one produces huge margins which make table-based documentation super hard to read. I used [mindoc](https://bitfragment.net/mindoc/)

```bash
mkdir -p html
for source in *.md; do
    [ -f "$source" ] || break
    output=${source/.md/.html}
    pandoc -s \
           -t html \
           -o html/$output \
           -f gfm \
           --template mindoc-pandoc.html \
           --metadata title=`basename $source` \
           $source
    sed -i 's/.md/.html/g' html/$output
done
```
Usage:
1. Start in repository root
1. `cd kubernetes/docs`
1. `wget https://raw.githubusercontent.com/bitfragment/mindoc/master/dist/mindoc-pandoc.html` or `curl https://raw.githubusercontent.com/bitfragment/mindoc/master/dist/mindoc-pandoc.html`
1. copy-paste the script above to your shell and press enter
1. when it finishes you should have `html` directory with docs that have working links (except for README.md as I didnt care about it, feel free to adjust it to include it)
1.  open a doc and navigate using working urls `xdg-open html/CoreV1Api.html`
