### ISSUE TITLE
client.EventsV1beta1Api().list_namespaced_event 无法获取返回结果

### ISSUE THREAD

**Issue by xiaowuwu163** [kubernetes-client/python#1221]
获取kube-apiserver 返回的结果集中，event_time 参数本身为空，而V1beta1Event 对象创建时，event_time属性默认必须传入event_time参数不为None才能创建，最终无法转转换为V1beta1Event 对象

**Comment by roycaihw** [comment]
IIUC you're saying that kube-apiserver responded `Event` object with empty `event_time` to the `list_namespaced_event` request. As a result this python client failed to parse the response because `event_time` is a [required field](https://github.com/kubernetes-client/python/blob/b5603d8ee2bc0861e26426d7c4a9f09b6adee644/kubernetes/client/models/v1beta1_event.py#L290-L291). 

This sounds like another occurrence of https://github.com/kubernetes-client/gen/issues/52. The fix needs to be done in upstream Kubernetes. kube-apiserver should either respond an `event_time` that is not `null`, or the field should be marked as [optional](https://github.com/kubernetes/kubernetes/blob/92e51c19017a9e417df291e469ffebb13b6b51e2/staging/src/k8s.io/api/events/v1beta1/types.go#L35-L36) instead of required.
