### ISSUE TITLE
list custom object for all namespaces

### ISSUE THREAD

**Issue by saswatac** [kubernetes-client/python#1377]
**What is the feature and why do you need it**:

Similar to the core_v1_api, the custom_objects_api should have a method `list_custom_object_for_all_namespaces`

**Describe the solution you'd like to see**:

`list_custom_object_for_all_namespaces` calls endpoint `/apis/{group}/{version}/{plural}` to get custom objects in all namespaces.

**Comment by roycaihw** [comment]
I think https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/CustomObjectsApi.md#list_cluster_custom_object is what you want. 

/close

**Comment by jparklab** [comment]
@roycaihw list_cluster_custom_object is to list *cluster scoped* custom objects, and the request is to have list_custom_object_for_all_namespaces similar to list_service_for_all_namespaces for services.
FYI, java client has a similar issue: https://github.com/kubernetes-client/java/issues/941

**Comment by jparklab** [comment]
Please disregard my comment above. list_cluster_custom_object worked for namespace scoped custom objects.

**Comment by roycaihw** [comment]
@jparklab ah you're right, I misread the original issue. Although `list_custom_object_for_all_namespaces` and `list_cluster_custom_object` happens to talk to the same API endpoint, it may be better to have a `list_custom_object_for_all_namespaces` method for documentation purpose. https://github.com/kubernetes-client/java/issues/941#issuecomment-623052547 is the right way to fix this issue. Since this issue affects multiple clients, would you mind filing an issue in https://github.com/kubernetes-client/gen about fixing the openapi spec?

**Comment by davidxia** [comment]
@roycaihw I created issue https://github.com/kubernetes-client/gen/issues/268
