### ISSUE TITLE
Cannot deploy on Kubernetes: deployments.apps is forbidden

### ISSUE THREAD

**Issue by MrPallaBall** [kubernetes-client/python#1410]
Hello,
here a Kubernetes message when I deploye a docker image from a gitlab repository:
`  {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"deployments.apps is forbidden: User \"system:serviceaccount:default:default\" cannot create resource \"deployments\" in API group \"apps\" in the namespace \"default\"","reason":"Forbidden","details":{"group":"apps","kind":"deployments"},"code":403}`

In my cose I use this lines:
```python
    config.load_incluster_config()
    apps_v1 = client.AppsV1Api()
    api_instance.create_namespaced_deployment(
        body=deployment,
        namespace='default')
```

my logs reports are:

```
INFO 2021-04-09 17:59:32,463 [delpoyment_services - line: 53] : Start to deploy inputs on Kubernetes
DEBUG 2021-04-09 17:59:32,463 [delpoyment_services - line: 43] : generic_job_deployment_json: { "container_name": "input-35-351-12", "deployment_name": "input-deployment-35-351-12", "requests_cpu": "100m", "requests_memory": "200Mi", "limits_cpu": "100m", "limits_memory": "200Mi"}
DEBUG 2021-04-09 17:59:32,566 [rest - line: 230] : response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"deployments.apps is forbidden: User \"system:serviceaccount:default:default\" cannot create resource \"deployments\" in API group \"apps\" in the namespace \"default\"","reason":"Forbidden","details":{"group":"apps","kind":"deployments"},"code":403}

ERROR 2021-04-09 17:59:32,567 [delpoyment_services - line: 173] : Cannot deploy pipeline on Kubernetes
```

my YML to deploy is:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: fusilli-kore-service
spec:
  selector:
    app: fusilli-kore
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fusilli-kore
spec:
  selector:
    matchLabels:
      app: fusilli-kore
  replicas: 1
  template:
    metadata:
      labels:
        app: fusilli-kore
    spec:
      containers:
      - name: fusilli-kore-container
        image: registry.gitlab.com/kdm-fusilli/fusilli.io-manager/fusilli.io-kore:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pods-list
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list", "get", "watch", "create", "update", "patch", "delete", "deletecollection"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pods-list
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  kind: ClusterRole
  name: pods-list
  apiGroup: rbac.authorization.k8s.io
```

Can anyone help me?

**Comment by MrPallaBall** [comment]
I have an update for all:

using the python crud example [here](https://github.com/kubernetes-client/python/blob/master/examples/deployment_crud.py) I have the same problem during the deployment step:
```
DEBUG 2021-04-10 09:46:56,901 [test_kubernetes - line: 11] : Start Create deploy ngnix in create_deployment_object function
DEBUG 2021-04-10 09:46:56,902 [test_kubernetes - line: 46] : Start Create Deployment ngnix in create_deployment function
DEBUG 2021-04-10 09:46:56,914 [rest - line: 230] : response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"deployments.apps is forbidden: User \"system:serviceaccount:default:default\" cannot create resource \"deployments\" in API group \"apps\" in the namespace \"default\"","reason":"Forbidden","details":{"group":"apps","kind":"deployments"},"code":403}
``` 

Just to understand all, I'm in GKE on Google Cloud where I create a cluster with teh same user that run the kubectl apply command

**Comment by MoShitrit** [comment]
Hey @MrPallaBall 
The issue you're seeing here is related to RBAC. You are trying to use the `default` service account, which be default- isn't allowed to do _anything_ when it comes to interacting with the k8s API.
Usually, when you create a script/app/any piece of code which should interact with the k8s API using a client (Go, Python, Java, or even simply using `curl` commands) - you have to properly authenticate. When you run your code from within a pod in k8s and configure your client (let's assume it's one of the official libraries to keep things standardize) - you use what's called the `inCluster` config- which means the pods uses the mounted `serviceAccount` token to interact with the k8s API. If you don't specify a `serviceAccountName` in your pod/deployment sped- the `default` service account is used, which as mentioned- isn't allowed to do anything. Based on the error you're getting- your code is trying to create a deployment, which is why you get the 403 back.
In order to solve this, you'll need to provide additional privileges to your service account using [RBAC](https://kubernetes.io/docs/reference/access-authn-authz/rbac/).
However - I _strongly_ advise that you DO NOT use the `default` service account for that purpose. If you grant additional privileges to the `default` service account - ANY pod in that namespace which doesn't have an explicit `serviceAccountName` field specified- would gain these additional privs, which would pose a risk to your cluster.
Instead- you'd want to create a separate service account for your app, grant the additional privileges to it and then specify that service account in the `serviceAccountName` field for your pod/deployment spec. You can read more about it [here](https://kubernetes.io/docs/reference/access-authn-authz/rbac/#service-account-permissions) and [here](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/).

**Comment by roycaihw** [comment]
/assign @MoShitrit 
Thanks!
