### ISSUE TITLE
interface for vertical pod autoscaler

### ISSUE THREAD

**Issue by saeid93** [kubernetes-client/python#1493]
Is there an interface like the one for [horizontal pod autoscaler](https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/AutoscalingV1Api.md#delete_namespaced_horizontal_pod_autoscaler) for vertical pod autoscaler in the python client library?

**Comment by MoShitrit** [comment]
[VerticalPodAutoscaler](https://github.com/kubernetes/autoscaler/blob/6e3e05d80ca17a6db14965c1bf8d33b0f6eb085f/vertical-pod-autoscaler/README.md#intro) is actually considered a custom resource and isn't a native k8s resource (more info in the linked documentation). Thus it doesn't have the same type of interface as HPA which is a first-class-citizen.
In order to interact with it, you'd want to use the [CustomObjectsApi](https://github.com/kubernetes-client/python/blob/d8f283e7483848647804eab345645106b6fb357d/kubernetes/docs/CustomObjectsApi.md).

**Comment by saeid93** [comment]
Thanks!
