### ISSUE TITLE
Can we use this with aws eks?

### ISSUE THREAD

**Issue by pavankumar1986** [kubernetes-client/python#1495]
Can we use this with aws eks and modify/create/delete kubernetes objects (deployment/secret/services, etc)?

**Comment by MoShitrit** [comment]
@pavankumar1986 Yep, you should be able to do that just fine with any hosted k8s solution.
As long as you provide proper RBAC privs, you should be good.

**Comment by pavankumar1986** [comment]
> @pavankumar1986 Yep, you should be able to do that just fine with any hosted k8s solution.
> As long as you provide proper RBAC privs, you should be good.

Thank you. I want to delete a secret, create a new one an then restart some deployments that are using the secrets. I am thinking of doing it via lambda. Can you please apis to delete/create secret and restart a deployment?

**Comment by MoShitrit** [comment]
> > @pavankumar1986 Yep, you should be able to do that just fine with any hosted k8s solution.
> > As long as you provide proper RBAC privs, you should be good.
> 
> Thank you. I want to delete a secret, create a new one an then restart some deployments that are using the secrets. I am thinking of doing it via lambda. Can you please apis to delete/create secret and restart a deployment?

Sure!
So to delete a secret, you'd want to use the [delete_namespaced_secret](https://github.com/kubernetes-client/python/blob/d8f283e7483848647804eab345645106b6fb357d/kubernetes/docs/CoreV1Api.md#delete_namespaced_secret) method under `CoreV1Api`. Unfortunately you'll have to view this markdown file as raw because it's too large for GitHub to render, but if you look at the actual code [here](https://raw.githubusercontent.com/kubernetes-client/python/d8f283e7483848647804eab345645106b6fb357d/kubernetes/client/api/core_v1_api.py) (simply search for `delete_namespaced_secret`) - you'll be able to see what this method takes as arguments, it's pretty straightforward. Same goes for `create_namespaced_secret`.

As far as restarting a deployment, you can take a look at [this](https://github.com/kubernetes-client/python/issues/1378#issuecomment-838884280) comment for a detailed example on how to best accomplish that.

Good luck! 😄
