### ISSUE TITLE
Binding Port Forward Socket To A File Path

### ISSUE THREAD

**Issue by the-wondersmith** [kubernetes-client/python#1501]
Following the example from [pod_portforward.py](https://github.com/kubernetes-client/python/blob/master/examples/pod_portforward.py#L97) I am able to get an object back whose type is `kubernetes.stream.ws_client.PortForward`. That object (as documented in the example) has a method called `socket` that can be called in order to get a `kubernetes.stream.ws_client.PortForward._Port._Socket` object back. *That* socket-like object has a property called `_socket` that supplies the underlying (read: "real") `socket.socket` which when inspected purports itself to be `<socket.socket fd={something}, family=AddressFamily.AF_UNIX, type=SocketKind.SOCK_STREAM, proto=0>`.

In the example, the returned socket-like object is used to monkeypatch `socket.create_connection` which is used by both http.client and  urllib.request and from all reports works like a charm. For my purposes though, it's not usable the same way. I'm trying to flesh out the test suite for a project that relies on [MySQL-connector](https://github.com/PyMySQL/mysqlclient). Specifically, I'm trying to set up a test fixture that will automatically forward the required port(s) to the correct pods for the tests to run.

From reviewing the documentation and comments in the mysqlclient repo, it looks like the `connect` method it supplies *will* accept a keyword argument for the location of a unix-like socket to use for the MySQL connection. Assuming everything works the same way that it does in the http.client example, binding the actual socket created by `kubernetes.stream.portforward` to a filesystem path and then supplying that path to the mysqlclient `connect` method should be all that I need.

I was hoping that someone would be able to point me in the right direction to figure out how to get the socket bound to a file path though. At the moment, every time I try to call `socket.bind("/tmp/mysql_sock")`, I get this error:

```
>>> sk._socket.bind("/tmp/mysql_sock")

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OSError: [Errno 22] Invalid argument
```

**Comment by roycaihw** [comment]
/assign @iciclespider

Could you help take a look to see if this can be supported? Thanks!

**Comment by iciclespider** [comment]
First, the returned port forward socket is already bound to the port in Kubernetes. You cannot call bind against an already bound socket. Second, it makes no sense to call `socket.bind` against a string value. This is a basic misunderstanding of how the socket api works.

This is a very specific use case that I do not see supporting in the client library.

This needs to be implemented in your code by opening the end point where you want to forward the port to and then handling the transfer of data between your local end point and the port forwarded socket.

**Comment by iciclespider** [comment]
I looked at that mysql python library, and it is implemented in C, and as such requires a port that it can open. Simplest to accomplish this is to use `kubectl` to expose a local port. The python client did not create this ability since that is what `kubectl` already does. The python port forwarding done here provides python code the ability to operate against remote kubernetes ports in python. It is not attempting to enable such access to non-python code, such as C.

**Comment by iciclespider** [comment]
After thinking this over, an possible enhancement would be to allow a "selectable" endpoint to be supplied that is used to transfer data to and from. This endpoint would be used instead of creating one using socket.socketpair. If not endpoint is supplied, then socket.socketpair is used to create one.
