### ISSUE TITLE
How to convert V1Ingress object to yaml file?

### ISSUE THREAD

**Issue by vemireddy-vaibhav** [kubernetes-client/python#1674]
I'm trying to convert v1Ingress object to standard yaml file. However comparing the saved file with it's manifest file using `kubectl get ing example -o yaml` shows different files. Any pointers to achieve this?

```
from kubernetes import client, config
import kubernetes.client
from kubernetes.client.rest import ApiException
import yaml
 

config.load_kube_config("k8s.yml")
v1 = client.NetworkingV1Api()
api_client = client.ApiClient()

namespace = "sample"

try:
    api_response = v1.list_namespaced_ingress(namespace)
 
    for ing in api_response.items:
        name = ing.metadata.name
        with open("{}.yml".format(name), "w") as f:
            yaml.dump(api_client.sanitize_for_serialization(ing), f, default_flow_style=False)

except ApiException as e:
    print("Exception when calling NetworkingV1Api->list_namespaced_ingress:", str(e), "\n")
```

**Comment by showjason** [comment]
Hi @vemireddy-vaibhav , I think it is a normal case,  the enssence of `kubectl` and `kubernetes-client` is calling the kubernetes API.
For `kubernetes-client`, it returns the native data of kubernetes
For `kubectl`, some keys in data of kubernetes will be sanitized by default, such as when you run the script you post above
,you will get data which contains `managedFields`, but `kubectl` will return the data without `managedFields`, it's because `kubectl` set the `--show-managed-fields=false` as default.

**Comment by vemireddy-vaibhav** [comment]
@showjason And it's not possible to set managed-fields to false in-case of `kubernetes-client` ?

**Comment by showjason** [comment]
> @showjason And it's not possible to set managed-fields to false in-case of `kubernetes-client` ?
I viewed the source code and did not find the `kubernetes-client` support to set managed-fields to false.

**Comment by vemireddy-vaibhav** [comment]
Alright, then looks like I have to use `kubectl` using `subprocess` module for now. Thanks for the help
