### ISSUE TITLE
minor issue with `requirements.txt`

### ISSUE THREAD

**Issue by jearls** [kubernetes-client/python#1746]
There is a requirement to have `setuptools` installed _when running `setup.py`_; however, `setuptools` is *not* required to actually run the client, as far as I can tell.  From my understanding, `setuptools` should not be part of `requirements.txt` if it's only used for building and is not needed in the distributed form.

**Comment by roycaihw** [comment]
Could you verify if the installation still works with the requirement removed? If that's the case, would you like to send a PR? Thanks!

**Comment by prescod** [comment]
Getting permission to sign the CLA is a bit of a hassle for me, but I did try to move "setuptools" from "requirements.txt" to "test-requirements.txt" and ran "pip install -e ." and everything seemed to go smoothly.

One reason to remove it is because when you use pip-tools with any project that derives from kubernetes-client, you get an error message like:

```
# The following packages are considered to be unsafe in a requirements file:
# setuptools
```

One of the vulnerability monitoring companies also has a beef with setuptools which causes a headache for vulnerability scanners at bigcos.

**Comment by xtaje** [comment]
The way the requirements files are being used has a couple other problems. They are not really supposed to be read and parsed into `setup.py`.  Moving it into `test-requirements.txt` still implies a circular dependency (kubernetes package installation -> setuptools -> kubernetes package installation).

Pip usually installs setuptools IIRC, so if you're using pip, then you will already have setuptools installed, so it happens to work OK for most users regardleess.

The intended way to use those files is described here https://packaging.python.org/en/latest/discussions/install-requires-vs-requirements/

**Comment by Shivansh2407** [comment]
Hey @prescod and @roycaihw , would you suggest cleaning up the requirements file, if no one's working on this? I'll verify this and make a PR for the same, if @prescod is not working on this currently. Thanks!
