### ISSUE TITLE
ConfigExceptions aren't made visible

### ISSUE THREAD

**Issue by merval** [kubernetes-client/python#2219]
**What is the feature and why do you need it**:
When loading the kube config, if any ConfigException is thrown it's caught and simply printed as an error message. This prevents any action being taken by the user when the exception is thrown. It also doesn't halt the application, which causes cascading errors.

**Describe the solution you'd like to see**:
Very simple fix: 
https://github.com/kubernetes-client/python/blob/e0234d3e7193aea4b4e8f487cab0f1228f4386d2/kubernetes/base/config/kube_config.py#L519-L520

Should be:
```
except ConfigException as e:
    raise ConfigException(e)
except Exception as e:
    logging.error(str(e))
```

**Comment by roycaihw** [comment]
The behavior is specific to exec plugin and was introduced in https://github.com/kubernetes-client/python-base/pull/75. Here is some context: https://github.com/kubernetes-client/python-base/pull/75#discussion_r215064743. The reason was to give a chance to other auth methods.

@yliaog Do you have concerns with the proposal? 

If we change the behavior, we should document it in the release notes in case people are depending on the behavior.

**Comment by yliaog** [comment]
I think the reason (give a chance to other auth methods) is still valid, what do you think @merval ?

**Comment by merval** [comment]
Yeah, that seems valid. In my case the ConfigException is thrown because the token is expired. I wonder of there should be a mechanism to raise the ConfigException if all other authentication methods fail.
