### ISSUE TITLE
[Query] Code Consistent Check

### ISSUE THREAD

**Issue by codevulture** [kubernetes-client/python#231]
Query1)
It would be consistent if : 
https://github.com/kubernetes-client/python-base/blob/7c8e59b58d9a769f1ca3f818aa91c8a6538b51b1/config/incluster_config.py#L73-L77 

would be implemented similar to :
https://github.com/kubernetes-client/python-base/blob/7c8e59b58d9a769f1ca3f818aa91c8a6538b51b1/config/incluster_config.py#L65

Is there any specific reason for the same?

Query2)
https://github.com/kubernetes-client/python-base/blob/7c8e59b58d9a769f1ca3f818aa91c8a6538b51b1/config/incluster_config.py#L30 why is '%' check used?

**Comment by mbohlool** [comment]
For 2) we followed golang's implementation here: https://golang.org/pkg/net/#JoinHostPort
To the actual reason it is '%' too, somebody should dig more.

**Comment by iamneha** [comment]
For 1) The purpose of doing this way because we are using `self.token` [here](https://github.com/kubernetes-client/python-base/blob/master/config/incluster_config.py#L83)

I believe there is no code consistency here.
@roycaihw can you please confirm and close this issue

**Comment by roycaihw** [comment]
@iamneha I think you're right.

What we are doing here is
- verifying in-cluster kubeconfig files, which are [token file and cert file](https://github.com/kubernetes-client/python-base/blob/949c39e6629871c34318426e10a3e3fcb793eb85/config/incluster_config.py#L23-L24)
- passing them to swagger-generated [Configuration](https://github.com/kubernetes-client/python/blob/4d4ce21265f58f79c55f6755e3ba60f4360ba172/kubernetes/client/configuration.py#L41-L46) object, which requires `ssl_ca_cert` as a **file name**, and `api_key` as a **token string**.

that's why for token file we read the content and for cert file we passed the file name.
