### ISSUE TITLE
Converting from JSON/Dict to a client Object

### ISSUE THREAD

**Issue by vishal-biyani** [kubernetes-client/python#340]
Hi, 
I am using the client-python to retrieve objects and then store them in a data store. So far things work pretty clean. 

Now I have an use case where I need to read the previously stored JSON representation of the object, create a client object and modify certain values and then create it in Kubernetes cluster. 

I did check out issue https://github.com/kubernetes-incubator/client-python/issues/63 which is pretty close. I wanted to check if there is an easy way to do this at all?

**Comment by mbohlool** [comment]
does this help? https://github.com/kubernetes-client/python-base/blob/168c5e761fc8a60a332e38342fda04350d64fe33/api_client.py#L216

**Comment by remram44** [comment]
bump; I need this

**Comment by remram44** [comment]
To follow on the resolution of #63: `to_dict()` uses different attribute names (e.g. snake_case instead of camelCase) so the resulting object don't work when sent to the API. The only way I've found to convert between models and JSON is this:
```
json_obj = client.api_client.sanitize_for_serialization(model_obj)
model_obj = client.api_client._ApiClient__deserialize(json_obj, 'V1Pod')
```
The model-to-json is sort of usable, but json-to-model uses a private API and needs you to map from json_obj['kind'] to the class name manually.

**Comment by micw523** [comment]
Checkout #574

**Comment by remram44** [comment]
@micw523: This only allows me to get raw JSON from a request, not to convert between JSON/Dict and models :cry:

**Comment by marcellodesales** [comment]
I saw that https://github.com/kubernetes-client/python/issues/574#issuecomment-405400414 works... It's awkward, but works...
