### ISSUE TITLE
Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)'

### ISSUE THREAD

**Issue by yokiy0828** [kubernetes-client/python#521]
from kubernetes import client, config

# Configs can be set in Configuration class directly or using helper utility
config.load_kube_config()

v1 = client.CoreV1Api()
print("Listing pods with their IPs:")
ret = v1.list_pod_for_all_namespaces(watch=False)
for i in ret.items:
    print("%s\t%s\t%s" % (i.status.pod_ip, i.metadata.namespace, i.metadata.name))

    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='192.168.0.1', port=6443): Max retries exceeded with url: /api/v1/pods?watch=False (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)'),))

env:python3.6

**Comment by yokiy0828** [comment]
OK, thx.

**Comment by rmacian** [comment]
Could you explain why is not working setting the property in the code ?

k8s=client.CoreV1Api()
k8s.api_client.configuration.verify_ssl = False ?

I am also getting this error in 2.7

MaxRetryError: HTTPSConnectionPool(host='myhost', port=443): Max retries exceeded with url: /api/v1/namespaces/dsmc-monitoring/events (Caused by SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)'),))

despite using the "official" requirements from:

https://github.com/kubernetes-client/python/blob/release-6.0/requirements.txt

**Comment by pengisgood** [comment]
I have the same issue. @vmulex 's workaround works for me. But it is not the recommended way obviously. Any other suggestions?

Thanks anyway.

**Comment by drnarahari** [comment]
This did not work for me. Still get `urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='XXX.XX.XX.XX', port=XXXX): Max retries exceeded with url: /api/v1/pods?watch=False (Caused by SSLError(SSLError(336265225, u'[SSL] PEM lib (_ssl.c:2718)'),))`
