### ISSUE TITLE
8.0 branch has support for python 3.7 but 6.0 branch doesn't

### ISSUE THREAD

**Issue by eastlondoner** [kubernetes-client/python#681]
kubernetes/client/apis/admissionregistration_api.py line 120 uses async as a named parameter. But that's not allowed in python 3.7

This has been changed in the 8.0 branch but not in other branches.

We can't use the 8.0 branch because it's not compatible with K8s 1.10 - which is the most up to date stable K8s available on GCP.

Could the fix be ported to the 6.0 branch and a new release cut?

**Comment by eastlondoner** [comment]
https://github.com/kubernetes-client/python/pull/682

**Comment by roycaihw** [comment]
@eastlondoner Have you tried 7.0.0 release? v7 releases should also contain the fix for Python 3.7 reserved keywords.

Also could you give some example on what API change made 8.0 branch be incompatible with k8s 1.10? 8.0 branch was generated against kubernetes 1.12 release. Since 7.0 branch was generated against kubernetes 1.11 release and the version skew is smaller, I'd expect 7.0.0 release works better with a k8s 1.10 cluster-- that being said, sometimes in Kubernetes we might have bad API change that breaks one-minor-version server-client skew guarantee.

**Comment by eastlondoner** [comment]
@roycaihw We use the Custom Resource Definition API and the 8.0 branch has incompatibilities there with 1.10

**Comment by roycaihw** [comment]
6.1.0 client has been released with Python 3.7 support: https://github.com/kubernetes-client/python/releases/tag/v6.1.0. Closing this issue

/close
