### ISSUE TITLE
Wrong Github link in auto-generated README 

### ISSUE THREAD

**Issue by roycaihw** [kubernetes-client/python#952]
**What happened (please include outputs or screenshots)**:
ref https://github.com/kubernetes-client/python/pull/931#discussion_r314434005

**What you expected to happen**:
the generated address should be `git+https://github.com/kubernetes-client/python.git`

**How to reproduce it (as minimally and precisely as possible)**:
run `scripts/update-client.sh`, and see the link in `kubernetes/README.md`

**Anything else we need to know?**:
This has been happening since we graduated this repo from `kubernetes-incubator/client-python` to `kubernetes-client/python`

The link seems to be composed as
```
git+https://github.com/GIT_USER_ID/GIT_REPO_ID.git
```
according to https://github.com/swagger-api/swagger-codegen/blob/master/samples/client/petstore/python/README.md#pip-install

however, the IDs that we use in `gen` repo look reasonable: https://github.com/kubernetes-client/gen/blob/795993978f8563a9c09089993be4d2b97d492eec/openapi/python.xml#L22-L23

**Environment**:
- OS (e.g., MacOS 10.13.6): MacOS 10.14.6
- Python version (`python --version`): 2.7.12
- Python client version (`pip list | grep kubernetes`): master branch HEAD

**Comment by palnabarun** [comment]
I investigated this issue. The problem seems to have a root in the following lines of codes in [kubernetes-client/gen:openapi/python.sh](https://github.com/kubernetes-client/gen/blob/master/openapi/python.sh#L57-58)

```
find "${OUTPUT_DIR}" -path "${OUTPUT_DIR}/base" -prune -o -type f -a -name \*.md -exec sed -i 's/\bclient/kubernetes.client/g' {} +
find "${OUTPUT_DIR}" -path "${OUTPUT_DIR}/base" -prune -o -type f -a -name \*.md -exec sed -i 's/kubernetes.client-python/client-python/g' {} +
```

Reference: https://github.com/kubernetes-client/gen/blob/master/openapi/python.sh#L57-58

What is happening here is the first line replaces all instances of `client` with `kubernetes.client`, and the second line replaces all wrongly replaced instances of `client-python` with the correct string. The first line replaces `kubernetes-client/python` with `kubernetes-kubernetes.client/python` resulting in the issue described above.

One quick solution to this would be to add a line after the above code:

```
find "${OUTPUT_DIR}" -path "${OUTPUT_DIR}/base" -prune -o -type f -a -name \*.md -exec sed -i 's/kubernetes-kubernetes.client/kubernbetes-client/g' {} +
```

I believe a long term solution is make the string replacement is the README templates robust and removing the above hacks.

**Comment by palnabarun** [comment]
Filed issue https://github.com/kubernetes-client/gen/issues/133 to track this.

**Comment by palnabarun** [comment]
Filed a PR https://github.com/kubernetes-client/gen/pull/134 to resolve this.

**Comment by palnabarun** [comment]
This issue has been fixed by https://github.com/kubernetes-client/gen/pull/134. We should close this now maybe.

**Comment by roycaihw** [comment]
Thanks for the fix!

/close
